[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/build"

[context.production.environment]
  REACT_APP_API_URL = "https://aiagent-backend-811233202539.us-central1.run.app"

[dev]
  command = "npm run start"
  port = 8888
